# Generated by Django 5.0 on 2023-12-23 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_client_workers_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='workers_number',
            new_name='worker_number',
        ),
    ]
